# Generated by Django 2.1.7 on 2019-03-22 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingtag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='meetingtag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meetingtag',
            name='meetup',
        ),
        migrations.RemoveField(
            model_name='meetingtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MeetingTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
