# Generated by Django 2.1.7 on 2019-03-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20190313_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingtag',
            unique_together={('tag', 'meetup')},
        ),
    ]
