# Generated by Django 2.0 on 2019-03-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20190309_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='created_by',
            new_name='user',
        ),
    ]
