# Generated by Django 2.1.7 on 2019-03-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20190311_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetup.Tag'),
        ),
    ]
