# Generated by Django 2.1.7 on 2019-03-11 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_auto_20190311_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
