# Generated by Django 2.1.7 on 2019-03-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_by', models.IntegerField()),
                ('date', models.DateField()),
                ('date_modified', models.DateField()),
            ],
        ),
    ]
