# Generated by Django 2.1.7 on 2019-03-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_by', models.IntegerField()),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField()),
            ],
        ),
    ]
