# Generated by Django 2.1.7 on 2019-03-11 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='meetup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Meeting'),
        ),
    ]
