# Generated by Django 2.1.7 on 2019-03-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
