# Generated by Django 2.1.7 on 2019-03-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20190307_0737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
