# Generated by Django 2.1.7 on 2019-03-21 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meetup', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='meetup.Meeting')),
                ('question', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='question.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('body', 'question', 'meetup')},
        ),
    ]
