# Generated by Django 2.1.7 on 2019-03-21 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answers',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetup.Meeting'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.Question'),
        ),
    ]
