# Generated by Django 2.1.7 on 2019-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
